#!/usr/bin/env python3

try:
    import matplotlib as mpl
    mpl.use('Agg')
    mpl.rcParams['lines.markersize'] = 2.0
    import pylab
except ImportError:
    pylab = None

try:
    import mplcyberpunk
    mpl.style.use('cyberpunk')
except ImportError:
    mplcyberpunk = None

import sqlite_functions as sqf


DATA_FMT_ERROR = (
    'Invalid data format. Supported formats:'
    ' (x, y), (key, value), (key, x, y)'
)

PLOT_TYPES = ('auto', 'plot', 'bar', 'scatter', 'semilogy', 'polar')


def check_row_format(row):
    try:
        if len(row) == 2:
            key = row[0]
            _ = float(row[1])
            if isinstance(key, str):
                return 'bar'
            key = float(key)
            return 'plot'
        elif len(row) == 3:
            _ = str(row[0])
            _ = isinstance(row[1], str) or float(row[1])
            _ = float(row[2])
            return 'plot'
    except Exception as ex:
        raise ValueError(DATA_FMT_ERROR, ex)
    raise ValueError(DATA_FMT_ERROR)


def plot(col_names, data, plot_type=None, fname=None):
    if pylab is None:
        raise RuntimeError('matplotlib is not installed')
    if not data:
        raise ValueError('no data')

    plot_type_auto = check_row_format(data[0])
    if plot_type is None or plot_type == 'auto':
        plot_type = plot_type_auto
    plot_ = getattr(pylab, plot_type)

    try:
        xtitle = col_names[-2]
        ytitle = col_names[-1]

        pylab.grid(True)
        pylab.xlabel(xtitle)
        pylab.ylabel(ytitle)

        if len(data[0]) == 2:
            xs = [d[0] for d in data]
            ys = [d[1] for d in data]
            if isinstance(xs[0], str):
                pylab.xticks(range(len(xs)), xs, rotation=90)
                pylab.subplots_adjust(
                    bottom=0.02 * max(len(key) for key in xs), top=0.9,
                    left=0.15, right=0.9
                )
                plot_(range(len(xs)), ys)
            else:
                plot_(xs, ys)
        elif len(data[0]) == 3:
            plot_data = {}
            plots = []
            keys = []
            xs = []
            xi = {}

            for key, x, y in data:
                try:
                    if isinstance(x, str):
                        try:
                            x = xi[x]
                        except KeyError:
                            xi[x] = len(xs)
                            xs.append(x)
                            x = xi[x]
                    plot_data[key][0].append(x)
                    plot_data[key][1].append(y)
                except KeyError:
                    plot_data[key] = ([x], [y])

            if xs:
                pylab.xticks(range(len(xs)), xs, rotation=90)
                pylab.subplots_adjust(
                    bottom=0.025 * max(len(key) for key in xs), top=0.9,
                    left=0.15, right=0.9
                )

            for key, args in plot_data.items():
                plt = plot_(*args, label=key)
                if isinstance(plt, (list, tuple)):
                    plt = plt[0]
                plots.append(plt)
                keys.append(key)

            pylab.legend(plots, keys)

        if mplcyberpunk is not None:
            mplcyberpunk.add_glow_effects()

        if fname is None:
            pylab.show()
        else:
            pylab.savefig(fname, dpi=200)
    finally:
        pylab.close()


def main():
    import os
    from argparse import ArgumentParser

    try:
        import pysqlite3 as sqlite3
    except ImportError:
        import sqlite3

    parser = ArgumentParser()
    parser.add_argument('-t', '--type',
                        choices=PLOT_TYPES,
                        default='auto',
                        help='plot type')
    parser.add_argument('-d', '--database',
                        default=os.path.expanduser('~/.bot/bot.db'),
                        help='database to query')
    parser.add_argument('-o', '--output', default=None,
                        help='output file')
    parser.add_argument('query')

    args = parser.parse_args()
    db = sqlite3.connect('file:%s?mode=ro' % args.database, uri=True)
    sqf.create(db, sqf.MATH)
    cursor = db.cursor()
    cursor.execute(args.query)
    plot(
        [desc[0] for desc in cursor.description],
        cursor.fetchall(),
        args.type,
        args.output
    )


if __name__ == '__main__':
    try:
        main()
    except Exception as ex:
        print(repr(ex))
